#!/bin/sh

# Set these paths appropriately

BIN="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/bin"
CMD="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/cmd"
LIB="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
