#!/bin/sh

# Set these paths appropriately

BIN="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/bin"
CMD="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/cmd"
LIB="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
