#!/bin/sh

# Set these paths appropriately

BIN="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/bin"
CMD="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/cmd"
LIB="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
