#!/bin/sh

# Set these paths appropriately

BIN="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/bin"
CMD="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/cmd"
LIB="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

