#!/bin/sh

# Set these paths appropriately

BIN="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/bin"
CMD="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/cmd"
LIB="/Users/luguangyi/Desktop/The_Termolator-master/TreeTaggerLinux/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/polish-abbreviations
PARFILE=${LIB}/polish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
